// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_buscar from "./routes/(platform)/buscar.tsx";
import * as $_platform_character_id_ from "./routes/(platform)/character/[id].tsx";
import * as $_platform_characters from "./routes/(platform)/characters.tsx";
import * as $_platform_favoritos from "./routes/(platform)/favoritos.tsx";
import * as $_platform_filter from "./routes/(platform)/filter.tsx";
import * as $_platform_houses from "./routes/(platform)/houses.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $FavButton from "./islands/FavButton.tsx";
import * as $FilterChars from "./islands/FilterChars.tsx";
import * as $HouseSelect from "./islands/HouseSelect.tsx";
import * as $SearchChars from "./islands/SearchChars.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/buscar.tsx": $_platform_buscar,
    "./routes/(platform)/character/[id].tsx": $_platform_character_id_,
    "./routes/(platform)/characters.tsx": $_platform_characters,
    "./routes/(platform)/favoritos.tsx": $_platform_favoritos,
    "./routes/(platform)/filter.tsx": $_platform_filter,
    "./routes/(platform)/houses.tsx": $_platform_houses,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
    "./routes/logout.tsx": $logout,
  },
  islands: {
    "./islands/FavButton.tsx": $FavButton,
    "./islands/FilterChars.tsx": $FilterChars,
    "./islands/HouseSelect.tsx": $HouseSelect,
    "./islands/SearchChars.tsx": $SearchChars,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
